mysql:
    dbms: "mysql"
    user: "user"
    pass: "secret"
    host: "0.0.0.0"
    port: "3306"
    dbname: "goSample"
    option: "?charset=utf8&parseTime=True&loc=Local"
postgres:
    dbms: "postgres"
    user: "user"
    pass: "secret"
    host: "0.0.0.0"
    port: "5432"
    dbname: "goSample"
    option: "sslmode=disable"
